---

- name: pull {{ gnbsim.docker.container_image }} image
  community.docker.docker_image:
    name: "{{ gnbsim.docker.container_image }}"
    source: pull
  become: true

- name: create {{ gnbsim.docker.container_image }} containers
  community.docker.docker_container:
    name: "{{ gnbsim.docker.container_prefix }}-{{ item }}"
    image: "{{ gnbsim.docker.container_image }}"
    command: sleep 1d
    state: started
  with_sequence: count={{ gnbsim.docker.container_count }}
  become: true
