---

- name: async start gnbsims
  community.docker.docker_container_exec:
    container: "{{ gnbsim.docker.container_prefix }}-{{ async_item }}"
    command: /bin/bash -c "rm -rf /gnbsim/bin/*.log & /gnbsim/bin/gnbsim"
  async: 45
  poll: 0
  loop: "{{ range(1, gnbsim.docker.container_count+1) }}"
  loop_control:
    loop_var: "async_item"
  register: async_results
  become: true
