---

- name: pull {{ gnbsim.docker.container.image }} image
  community.docker.docker_image:
    name: "{{ gnbsim.docker.container.image }}"
    source: pull
  when: inventory_hostname in groups['gnbsim_nodes']
  become: true

- name: create {{ gnbsim.docker.container.image }} containers
  community.docker.docker_container:
    name: "{{ gnbsim.docker.container.prefix }}-{{ item }}"
    image: "{{ gnbsim.docker.container.image }}"
    network_mode: "{{ gnbsim.network.macvlan_network_name }}"
    command: sleep 1d
    state: started
  with_sequence: count={{ gnbsim.docker.container.count }}
  when: inventory_hostname in groups['gnbsim_nodes']
  become: true


# - name: Add a container to a network, leaving existing containers connected
#   docker_network:
#     name: "{{ gnbsim.network.macvlan_network_name }}"
#     connected:
#       - "gnbsim-{{ item.key }}"
#     appends: yes
#   with_dict: "{{ gnbsim.simulator.gnbsims }}"
#   when: inventory_hostname in groups['gnbsim_nodes']
