---

- name: pull {{ gnbsim.docker.container.image }} image
  community.docker.docker_image:
    name: "{{ gnbsim.docker.container.image }}"
    source: pull
  become: true

- name: create {{ gnbsim.docker.container.image }} containers
  community.docker.docker_container:
    name: "{{ gnbsim.docker.container.prefix }}-{{ item }}"
    image: "{{ gnbsim.docker.container.image }}"
    command: sleep 1d
    state: started
  with_sequence: count={{ gnbsim.docker.container.count }}
  become: true
